
apiVersion: v1
kind: Pod
metadata:
  name: trino-java
  namespace: ed-testing
  labels:
    app: ed-testing
spec:
  containers:
    - name: trino-java
      image: edswarchitect/edbrown-trino-java:1.0.0-SNAPSHOT
