additionalCatalogs:
  kafka: |-
    connector.name=kafka
    kafka.table-names=citibike
    kafka.default-schema=citi
    kafka.hide-internal-columns=false
    kafka.nodes=my-cluster-kafka-bootstrap:9092
    kafka.table-description-dir=etc/schemas
  entity: |-
    connector.name=kafka
    kafka.table-names=entity
    kafka.default-schema=comms-broker
    kafka.hide-internal-columns=false
    kafka.nodes=my-cluster-kafka-bootstrap:9092
    kafka.table-description-dir=etc/schemas
additionalNodeProperties:
  - org.apache.kafka=INFO

server:
  log:
    trino:
      level: INFO